# Make sure that
#   * the revs specified here match requirements-dev.txt
#   * the makefile checks the same files as pre-commit

ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
        - --diff
        - --check
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: v2.13.9
    hooks:
    -   id: pylint
        name: pylint
        exclude: ^tests/
        args:
        - --rcfile=setup.cfg
        #  run pylint across multiple cpu cores to speed it up-
        - --jobs=0  # See https://pylint.pycqa.org/en/latest/user_guide/run.html?#parallel-execution to know more
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
    -   id: mypy
        exclude: ^tests/
        additional_dependencies:
            - types-ujson
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    -   id: pyupgrade
        args:
          - --py37-plus
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
        args:
        - --diff
        - --check
